### ISSUE TITLE
Kourier with cert-manager and HTTP01 challenges

### ISSUE THREAD

**Issue by tiangolo** [knative-extensions/net-kourier#1304]
## Summary

I'm trying to figure out what is the right way to configure **Kourier** with **cert-manager** to get custom domains using an **HTTP01** challenge.

## What I Understand

I already read all the relevant Knative docs I could find, README here, searched in issues in Knative and here, searched online, tried several combinations, but haven't been able to find out how to do it.

Reading issues here and there I'm concluding that autoTLS was renamed to external-domain-tls, so I'm assuming that info related to autoTLS is somewhat related to external-domain-tls as well.

I understand that Kourier supports a [hardcoded](https://github.com/knative-extensions/net-kourier/issues/135#issuecomment-668620817) TLS certificate for everything set up externally, using the TLS env vars (`CERTS_SECRET_NAMESPACE`, `CERTS_SECRET_NAME`).

I understand that to support TLS for additional domains it would be done through external-domain-tls (ref: the same thread above: https://github.com/knative-extensions/net-kourier/issues/135#issuecomment-672836117). And I understand that Kourier supports external-domain-tls.

I'm not sure what does external-domain-tls actually enable (which features it covers and which it doesn't). But I understand that however is the way to do it, it would have to be through external-domain-tls.

I understand that for external-domain-tls to work, I still need to create a ClusterIssuer.

For the ClusterIssuer with cert-manager, to configure an http01 challenge, it seems I still need to configure some ingress, e.g. an `ingressClassName` or a `class`.

## What I Don't Know

I don't know how to configure the ingress for the http01 challenge in the ClusterIssuer to use Kourier, not sure what `class` should I use or what should I try doing. All the cert-manager examples are using other tools, e.g. Nginx, or Traefik.

The Kourier docs/README points to Knative's docs, but the docs in Knative about it only have an example for a self-signed certificate.

I suspect one or more of the things I'm assuming above are incorrect and maybe the way to do this is completely different.

## What Already Worked

I was able to install and configure cert-manager, I configured an Issuer using a DNS01 challenge (with Cloudflare), I was able to get a wildcard certificate.

I was able to configure this wildcard certificate as the "hardcoded" main certificate for Kourier.

I was able to have multiple Knative services served with HTTPS using that wildcard certificate, with subdomains.

I think this would confirm that Knative, Kourier, cert-manager, seem to be correctly installed. But I'm still missing the http01 challenge with Kourier... :sweat_smile: 

## What I Already Tried

I thought that, as I have to configure Knative to use Kourier by setting the `ingress-class: kourier.ingress.networking.knative.dev`, maybe I could try using that class for the ClusterIssuer, as:

```yaml
class: kourier.ingress.networking.knative.dev
```

I tried with and without external-domain-tls enabled, but I don't see a way to make it work.

## cert-manager integration

I'm now doubting if the cert-manager integration is still available in Knative in general or not...

I see the docs about configuring the cert-manager integration here: https://knative.dev/docs/serving/encryption/configure-certmanager-integration/#configuring-issuers

In there there's an instruction to modify the config map `config-certmanager`:

```
kubectl edit configmap config-certmanager -n knative-serving
```

But that config map doesn't seem to be available. The references I was able to find point to this repo: https://github.com/knative-extensions/net-certmanager

But the repo is archived and there's no info in the README or any issue about why it was archived, or what would replace it.

Nevertheless, the Knative docs don't mention an alternative, a successor tool, or a deprecation of some cert-manager integration, so I'm not sure what else to try next.

---

Any pointers would be appreciated!

**Comment by tiangolo** [comment]
## New Info

I found that net-certmanager was integrated into the main Knative Serving: https://github.com/knative/serving/pull/15066

So I wasn't missing another thing to install.

## What Was Wrong

The main thing I had wrong was an old installation (from a few months ago), right before net-certmanager was integrated into the main Knative Serving, and right before net-certmanager was archived.

I had Knative and Kourier version 1.14.1, now I have 1.16.0.

After updating, I got much clearer errors in the events, the certmanager resources were created, etc. And I could debug the rest. I suppose that it was because the new version included the certmanager integration, before that nothing was handling those configs (I suppose).

## Configs

About the ClusterIssuer, I thought I needed to define some type of ingress, but looking at the source code and source tests in Knative Serving I found that it can be an empty object, so, this is the config that ultimately worked:

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01-production
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: certs@example.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-http01-production
    solvers:
    - http01:
        ingress: {}
      selector: {}
```

Then I referenced it by name (`letsencrypt-http01-production`) in a Kustomize file:

```yaml
apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: config-certmanager
  namespace: knative-serving
data:
  issuerRef: |
    kind: ClusterIssuer
    name: letsencrypt-http01-production
```

**Note**: this is a Kustomize patch file, it would only update the defined configs in the existing file, it doesn't declare everything else.

I also updated the `config-network` config map in another Kustomize patch to enable external-domain-tls:

```yaml
apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
data:
  external-domain-tls: Enabled
```

After this it finally worked. :rocket: 

I didn't need to change anything else in how Kourier is connected to the outside world (e.g. cloud load balancer in my case), or extra ingresses, etc.

This solves my problem, so I'll close this issue now. Cheers! :cake:
